id: celegans_embryo

file_name: "Celegans_embryo_dataset.h5ad"

obs_cell_type: "cell.type"

obs_batch: batch

var_feature_id: id

var_feature_name: gene_short_name

dataset_name: "C Elegans Embryo Atlas v1"

dataset_url: "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE126954"

dataset_reference: packer2019lineage

dataset_summary: "profiling the transcriptomes of 86,024 single embryonic cells from C. elegans"

dataset_description: "C elegans dataset produceed by Packer et al (2019), with poor quality and unlabeled cells removed"

dataset_organism: caenorhabditis_elegans

normalization_methods:
  - log_cp10k
  - sqrt_cp10k
  - l1_sqrt

output_dataset: $id/dataset.h5ad

output_meta: $id/dataset_metadata.yaml

output_raw: force_null

output_normalized: force_null

output_pca: force_null

output_hvg: force_null

output_knn: force_null

