id: human_lung

file_name: "Lung_atlas_public.h5ad"

obs_cell_type: cell_type

obs_batch: batch

obs_tissue: location

layer_counts: counts

dataset_name: "Human Lung Atlas"

dataset_url: "https://figshare.com/ndownloader/files/24539942"

dataset_reference: luecken2022benchmarking

dataset_summary: "three datasets sample two distinct spatial locations (airway and parenchyma)"

dataset_description: "Lung atlas dataset compiled by Luecken et al (2022) for benchmarking."

dataset_organism: homo_sapiens

normalization_methods:
  - log_cp10k
  - sqrt_cp10k
  - l1_sqrt

output_dataset: dataset.h5ad

output_raw: dataset_raw.h5ad

output_normalized: dataset_normalized.h5ad

output_pca: dataset_pca.h5ad

output_hvg: dataset_hvg.h5ad

output_knn: dataset_knn.h5ad

