id: human_lung

file_name: "Lung_atlas_public.h5ad"

obs_cell_type: cell_type

obs_batch: batch

obs_tissue: location

var_feature_id: gene_ids

layer_counts: counts

dataset_name: "Human Lung Atlas"

dataset_url: "https://figshare.com/ndownloader/files/24539942"

dataset_reference: luecken2022benchmarking

dataset_summary: "three datasets sample two distinct spatial locations (airway and parenchyma)"

dataset_description: "Lung atlas dataset compiled by Luecken et al (2022) for benchmarking."

dataset_organism: homo_sapiens

normalization_methods:
  - log_cp10k
  - sqrt_cp10k
  - l1_sqrt

output_dataset: $id/dataset.h5ad

output_meta: $id/dataset_metadata.yaml

output_raw: force_null

output_normalized: force_null

output_pca: force_null

output_hvg: force_null

output_knn: force_null

