id: trevino_atac

file_name: "Trevino.h5ad"

obs_cell_type: label

obs_batch: sample

obs_tissue: skip

var_feature_id: skip

var_feature_name: skip

dataset_name: "Trevino Cortex"

dataset_url: "https://www.cell.com/cell/fulltext/S0092-8674(21)00942-9"

dataset_reference: trevino2021

dataset_summary: "Chromatin and gene-regulatory dynamics of the developing human cerebral cortex at single-cell resolution"

dataset_description: "Using mapping of cluster labels to cell types from supplement, and sample ID as batch"

dataset_organism: homo_sapiens

normalization_methods:
  - log_cp10k

output_dataset: $id/dataset.h5ad

output_meta: $id/dataset_metadata.yaml

output_raw: force_null

output_normalized: force_null

output_pca: force_null

output_hvg: force_null

output_knn: force_null

